# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82ee6bde4564cc5524b2c56a55946ebca5f8eae52d80ea9f4579fbbe84f126615780c0fbb1d0e2926ff288489ee1594aaa827bf0093774bfa599b9fb181e6ac7

test:
  secret_key_base: d9ffc304a4be46c5db383a0cb6943fc291786237c3e0b4430f5ed0e5d8b1291661f76aa7c4b31025a0d271b0ee86dcab9d7eab5270f7b1acf1d23a5f44716ef3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
